# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "n1" do |n1|

    n1.vm.box = "debian/contrib-jessie64"
    n1.vm.hostname = "n1"

    n1.vm.box_check_update = false

    n1.vm.network "forwarded_port", guest: 8080, host: 8090

    n1.vm.network "private_network", ip: "192.168.33.10"

    n1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    n1.vm.provision "shell", inline: <<-SHELL
      sudo sed -i '/PasswordAuthentication no/c\PasswordAuthentication yes' /etc/ssh/sshd_config
      sudo service ssh restart
      sudo echo '127.0.1.1       n1' | sudo tee -a /etc/hosts
      sudo echo '192.168.33.11       n2' | sudo tee -a /etc/hosts
    SHELL
  end

  config.vm.define "n2" do |n2|
      n2.vm.box = "debian/contrib-jessie64"
      n2.vm.hostname = "n2"

      n2.vm.box_check_update = false

      n2.vm.network "forwarded_port", guest: 8080, host: 8091

      n2.vm.network "private_network", ip: "192.168.33.11"

      n2.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end

      n2.vm.provision "shell", inline: <<-SHELL
        sudo sed -i '/PasswordAuthentication no/c\PasswordAuthentication yes' /etc/ssh/sshd_config
        sudo service ssh restart
        sudo echo '127.0.1.1       n2' | sudo tee -a /etc/hosts
        sudo echo '192.168.33.10       n1' | sudo tee -a /etc/hosts
      SHELL
    end

end
